### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by f-beerlage** [CarlosTrujilloGonzalez/FreeFluidsModelica#32]
Where can I find a current documentation about this project? 

Regards

**Comment by CarlosTrujilloGonzalez** [comment]
I try to maintain it inside the project, as documentation that you can view in the documentation browser of the class. The coverage is very irregular, for example you will find few models commented in the package Vessels, but for the Pumps and Valves packages it is not the case.

**Comment by f-beerlage** [comment]
Ok thank you.
