### ISSUE TITLE
Examples do not work

### ISSUE THREAD

**Issue by f-beerlage** [CarlosTrujilloGonzalez/FreeFluidsModelica#33]
Furthermore, I have noticed that the following examples do not work. I think the connection to that block is missing. 
Since I don't know how to use the library, I wasn't able to fix it myself. 

Under Vessels:

- VesselSimpleWithPump
- VesselDetailedWithPVvalve
- VesselDetailedPressureRelief

**Comment by CarlosTrujilloGonzalez** [comment]
Yes, I changed the reference in order to do some tests and forgot to restore the original reference. I have already corrected the issue and I plan to update the repository today or tomorrow.
Thanks for the information.
